
SELECT 
DD.DDOC_ID,DD.SELLER_REG_NO,DD.SELLER_NAME,DD.BUYER_REG_NO,
DD.BUYER_NAME ,SDOC.DOC_TYPE_DESC AS DOC_TYPE,DD.FORM_ID_SALE,DD.FORM_ID_PURCHASE
FROM IRIS_STRV.DOMESTIC_DOCUMENTS DD
JOIN IRIS_STRV.FORM_SALE_INVOICES SI
ON SI.DDOC_ID = DD.DDOC_ID
JOIN IRIS_STRV.SA_DOC_TYPES SDOC
ON DD.DOC_TYPE_ID = SDOC.DOC_TYPE_ID
WHERE DD.DOC_STAGE_CODE ='4'
--AND BUYER_REG_NO ='3520220000000'
;


SELECT * FROM IRIS_STRV.SA_DOC_TYPES ;

SELECT * FROM IRIS_STRV.DOMESTIC_DOCUMENTS -- 295 rows
WHERE DOC_STAGE_CODE ='4' 
--and FORM_ID_PURCHASE in (SELECT form_id FROM IRIS_STRV.FORM_7ABC)
;

SELECT * FROM IRIS_STRV.FORM_SALE_INVOICES;

SELECT * FROM IRIS_STRV.DOMESTIC_DOCUMENTS
WHERE INVOICE_STATUS =
SELECT * FROM IRIS_STRV.DOCUMENT_STAGES;

SELECT * FROM IRIS_STRV.DOCUMENT_STATUS;

SELECT * FROM IRIS_STRV.FORM_7ABC  --729 rows
WHERE AMOUNT_CODE ='100111';
