SELECT 
	STG.DOC_STATUS_DESC AS STATUS,SACT.DESCRIPTION AS Collectorate,GDTYPE.DESCRIPTION AS GD_TYPE,EXP.GD_NO AS GD_Number,
    EXP.GD_Date, EXP.HS_Code,EXP.GD_VALUE AS Values_in_Pak_Rupees,EXP.MR_VALUE AS Value_of_Good_Actually_Shipped,
    EXP.SS_VALUE AS Value_of_Short_Shipment,EXP.MR_NO AS MR_Consignment_Number,EXP.MR_DATE AS MR_Consignment_Date									
FROM IRIS_STRV.FORM_EXPORT_DETAILS EXP
FULL JOIN   IRIS_STRV.SA_CUSTOM_COLLECTORATES SACT
ON EXP.COLLECTORATE_ID = SACT.COLLECT_ID
FULL JOIN IRIS_STRV.DOCUMENT_STATUS STG
ON EXP.CASE_STATUS_CODE = STG.DOC_STATUS
FULL JOIN IRIS_STRV.SA_CUSTOM_GD_TYPES GDTYPE
ON GDTYPE.GD_TYPE_ID = EXP.GD_TYPE;








SELECT * FROM IRIS_STRV.DOCUMENT_STATUS;-- DOC STATUS

SELECT * FROM IRIS_STRV.FORM_EXPORT_DETAILS; -- annex-d export data 

SELECT * FROM IRIS_STRV.FORM_GDI_DETAILS; --ANNEX-B IMPORT DATA

SELECT * FROM IRIS_STRV.FORM_PRM_DETAILS;

SELECT * FROM IRIS_STRV.SA_CUSTOM_GD_TYPES; --GD TYPES DATA

SELECT * FROM IRIS_STRV.sa_custom_collectorates;-- COLLECTORATES DATA

