SELECT 
  PI.FIXED_ASSET,PI.INADMIS_TAX as InAdmissible,DST.DOC_STATUS_DESC AS STATUS, DD.SELLER_REG_NO,DD.SELLER_NAME,VATAX.TAXPAYER_DESC as Supplier_Type,
  DD.BUYER_REG_NO,DD.BUYER_NAME,STATE.STATE_PROVINCE_DESC AS Sale_Origination_Province,STATE.STATE_PROVINCE_DESC AS Destination_of_Supply,
  DOC.DOC_TYPE_DESC AS TYPE ,PI.DOC_NO as DOC_Number ,PI.DOC_DATE,VATTR.TRANSACTION_DESC AS PURCHASED_TYPE ,DD.HS_CODE ,VAT.RATE_DESC AS RATE,
  UM.DESCRIPTION AS UOM,PI.QTY as Quantity,PI.PURCHASE_VALUE  as Value_of_Purchases,PI.VAT_AMOUNT as Sales_Tax,DD.RETAIL_PRICE as Fixed_Retail_Value,
  PI.VAT_WITHHELD as ST_Withheld, DD.EXTRA_TAX,SRO.SRO_DESC AS SRO_Schedule_No,DD.SRO_ITEM_ID as Item_Sr_No,PI.Further_Tax,DD.INPUT_CREDIT_NOTALLOW,PI.FED_CHARGED
  FROM IRIS_STRV.DOMESTIC_DOCUMENTS DD  
FULL JOIN  IRIS_STRV.FORM_PURCHASE_INVOICES PI
ON DD.DDOC_ID = PI.DDOC_ID
FULL JOIN IRIS_STRV.SA_VAT_RATE_CODE VAT
ON VAT.RATE_ID = PI.RATE_ID
FULL JOIN IRIS_STRV.DOCUMENT_STATUS DST
ON DD.CASE_STATUS_CODE = DST.DOC_STATUS
FULL JOIN IRIS_STRV.SA_DOC_TYPES DOC
ON PI.DOC_TYPE_ID = DOC.DOC_TYPE_ID 
FULL JOIN IRIS_STRV.SA_VAT_TRANSACTION_TYPE_CODE VATT
ON VATT.TRANSACTION_TYPE_ID = DD.TRANSACTION_TYPE_ID
FULL JOIN IRIS_STRV.SA_VAT_UOM UM
ON  UM.UOM_ID = VAT.UOM_ID
FULL JOIN iris_strv.SA_VAT_TAXPAYER_TYPE_CODE VATAX
ON DD.BUYER_TYPE_ID = VATAX.TAXPAYER_TYPE_ID
FULL JOIN IRIS_STRV.SA_STATES_PROVINCES STATE
ON STATE.STATE_PROVINCE_CODE = DD.BUYER_PROVINCE_ID
FULL JOIN IRIS_STRV.SA_REG_VERIFICATION_STATUS REGVER
ON REGVER.VERIFICATION_ID = DD.BUYER_TRUST_STATUS
FULL JOIN IRIS_STRV.SA_VAT_TRANSACTION_TYPE_CODE VATTR
ON VATTR.TRANSACTION_TYPE_ID = DD.TRANSACTION_TYPE_ID
JOIN IRIS_STRV.SA_VAT_SRO_CODE SRO
ON SRO.SRO_ID = DD.SRO_ID
FULL JOIN IRIS_NEW.WORKFLOW WF
ON DD.FORM_ID_SALE = WF.TRANSACTION_ID
;







SELECT * FROM IRIS_STRV.SA_VAT_SRO_CODE;
SELECT * FROM IRIS_STRV.FORM_PURCHASE_INVOICES;
SELECT * FROM IRIS_STRV.SA_VAT_TRANSACTION_TYPE_CODE;
SELECT * FROM IRIS_STRV.SA_REG_VERIFICATION_STATUS;
SELECT * FROM IRIS_STRV.SA_STATES_PROVINCES;
select * from iris_strv.SA_VAT_TAXPAYER_TYPE_CODE;
SELECT * FROM IRIS_STRV.DOMESTIC_DOCUMENTS;
SELECT * FROM IRIS_STRV.SA_VAT_RATE_CODE;
SELECT * FROM IRIS_STRV.SA_DOC_TYPES;
SELECT * FROM IRIS_STRV.DOCUMENT_STATUS;
SELECT * FROM IRIS_STRV.SA_VAT_UOM;
SELECT * FROM IRIS_STRV.SA_VAT_SRO_ITEM_CODE;
SELECT * FROM IRIS_STRV.SA_VAT_HSCODES;
SELECT * FROM IRIS_STRV.SA_VAT_HSCODE_SERVICES;
SELECT * FROM IRIS_STRV.SA_VAT_ITEM_DESC_CODE;

